In [60]:
#Task1
#import arr01 and arr02 as required
import numpy as np
arr01 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
arr02 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
#use interset1d to select the common numbers in both arr01 and arr02
common = np.intersect1d(arr01, arr02)
common


array([2, 4])

In [39]:
#Task 2
#import a array with 15 numbers first, then use reshape to get the 5 rows, 3 numbers in each row shape, then ues 'array+1' to make sure 
#the first number in each dimension increaced by 1.
import numpy as np 
arr = np.arange(15).reshape(5,3)
(arr+1).T
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [46]:
#Task 3, step1
#import arr01 and arr02
arr01 = np.array([12, 5, 7, 15, 3, 1, 8]) 
arr02 = np.array([14, 6, 3, 11, 19, 12, 5])
#use 'intersectld' can select the common numbers in arr01 and arr02
common = np.intersect1d(arr01,arr02)

#Task 3, step2
#use‘setdiffld’to get the uncommon numbers in arr01
uncommon = np.setdiff1d(arr01,common)
uncommon

array([ 1,  7,  8, 15])

In [31]:
import numpy as np 
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([3, 0, 1, 7, 5, 9, 6, 4, 8, 2])

In [29]:
#Task4-the cumulative miles
#using google map to cheak the distance from New York to Key West by cyclying is 1547 miles. We can use'random.randint(a,b)' to choose-
#-35 numbers 'n' randomly from range (a,b), a is the minmum and b is the maxmum number in this range, for any n is :a <= n <= b
import numpy as np
arr = np.random.randint(1, 1547, 35)
#choose any 4 numbers in the above array and make sure that the number is same as the next number. 
for i in np.random.randint(1, 34, 4):
    arr[i] = arr[i+1]
#make sure the last number is the total miles by cyclying between new york and west key:1547
arr[34] = 1547
#make sure the cumulative number for everyday is in a ascending order, we use'sort'here. Then we get the array to record the cumulative-
#-mailes for each day
arr_cumulative = np.sort(arr)
arr_cumulative

array([ 117,  117,  119,  154,  393,  439,  452,  454,  475,  531,  553,
        668,  704,  862,  942, 1053, 1068, 1068, 1068, 1089, 1185, 1205,
       1264, 1357, 1378, 1411, 1425, 1426, 1443, 1478, 1478, 1533, 1534,
       1539, 1547])

In [30]:
#Task4-the each day miles
#the first day mile is the first number in arr_cumulative
i = arr_cumulative[0]
#from the second number in each_day miles, the number is the difference between the numbers, we use diff here
each_day = np.append(i, np.diff(arr_cumulative))
each_day

array([117,   0,   2,  35, 239,  46,  13,   2,  21,  56,  22, 115,  36,
       158,  80, 111,  15,   0,   0,  21,  96,  20,  59,  93,  21,  33,
        14,   1,  17,  35,   0,  55,   1,   5,   8])

In [48]:
#Task5
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)
print(nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':


According to the website, we know that the 4 column data here represent 'Year','New York City Population','NYC comsumpetion million gallons per day','gallons per person per day'.

In [50]:
#Task5-01
#here we use'max' to get the maxmium data in the 3rd column
nyc_water[:,2].max()

1512.0

In [51]:
#Task5-02
#NumPy's shape command is one way to find out, so we use shape here
nyc_water.shape[0]

39

In [61]:
#Task5-03
#just use the 'std' syntax here to get the standard deviation for the 4th column data here 
arr_std = np.std(nyc_water[:,3])
arr_std

31.51894330370624

In [57]:
#Task5-04
#use 'diff' to the 2ed column here,diff function can caculate the variable direactly from the data and the next data.
pop_diff = np.diff(nyc_water[:,1])
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
